services:
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend   
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./database:/backend/database
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - YPERSISTENCE=./database